### ISSUE TITLE
Hardware 'Sync' button

### ISSUE THREAD

**Issue by adwiebe** [scruss/Powermon433#9]
Add a button to Arduino that toggles the TX_ID_LOCK at runtime. Maybe put the D13/Status LED into a blinking mode until a ID is found, then set LED on.

**Comment by adwiebe** [comment]
I'm new to Github - TL;DR - I forked the project and added storing the ID in firmware. https://github.com/adwiebe/Powermon433

(I also removed the rf69 support as I don't use it and needed the pins for status indicators)

I hacked in the button to my circuit this morning: https://www.instagram.com/p/BOlCi-QBi8N

**Comment by adwiebe** [comment]
Dang - wrong button. Sorry, didn't mean to close it. I think the changes should be merged back into your repository, right?

**Comment by scruss** [comment]
No worries. Glad you've made the effort to add features. I think we can close this
